# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy package and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
# Install dependencies and build
RUN npm install --ignore-scripts
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app
# Copy built files
COPY --from=builder /app/dist ./dist
# Copy production deps manifest and install
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts
# Provide empty .env for dotenv
RUN touch /app/.env

# Entrypoint
ENTRYPOINT ["node", "dist/index.js"]
